#This file tells travis what we want to do with our code
language: generic
sudo: required
#services required
services:
  - docker

#what to do before installing.
#We have build out Dockerfile.dev file and tagged a name with it as well
#We use the Dockerfile.dev because it has test suite as well
before_install:
  - docker build -t gargvatsal2000/docker-react -f Dockerfile.dev .

#This tells travis how to ru our test-suite
#In general, to run test, we use: docker run <image_id> npm run test
script:
  - docker run -e CI=true gargvatsal2000/docker-react npm run test
