version: '3'
services:
  web:
    #we are adding this because on realoding, my react app was not updating earlier. after adding this, it updates on making changes in app.js
    environment:
      - CHOKIDAR_USEPOLLING=true
      #build: .  -> cannote use this since our dockerfile name is changed
    build:
      context: . #the folder from which we want to get the file. since it is in same folder, we use .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - . :/app #map the current folder outside of container to folder inside the container
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - . :/app
    command: ['npm', 'run', 'test'] #overrides the npm run start command
